### ISSUE TITLE
When trying to link to google, getting a page not found

### ISSUE THREAD

**Issue by theCheek** [hassio-addons/addon-phlex#51]
# Problem/Motivation

Trying to get google assistant to talk with flex.tv

## Expected behavior

FlexTV (self hosted) --> settings --> Account Linking --> Link Google -->login to google --> control Flex with google assistant

## Actual behavior

FlexTV (self hosted) --> settings --> Account Linking --> Link Google --> Page Not Found

## Steps to reproduce

I'm guessing its the same issue spoken of here, so might be a universal issue and not just in hassio?
[https://github.com/d8ahazard/FlexTV/issues/15](url)

**Comment by fortepc** [comment]
My best guess is that the version of Phlex is outdated, the API url has changed. That much is for sure. Flex TV was also removed from Google Assistant... 

Looks like Phlex may be dead for now 😢
