### ISSUE TITLE
Web interface spins forever after login

### ISSUE THREAD

**Issue by nhorvath** [hassio-addons/addon-phlex#54]
# Problem/Motivation
After going to the web ui and authorizing it to connect to my plex account it goes back to phlex and just spins forever on the screen with a random movie background image. I don't see any javascript errors in the console or pending web requests in network tab.
Hard refresh of page makes no difference except different background image.
Restarting addon brings me back to login process but spins forever like before after completing it.

## Expected behavior
Web UI to load

## Actual behavior
See Problem

## Steps to reproduce
I'm not sure, it's a brand new install for me. I do have a rather large plex library.

 Add-on version: 1.1.0
 You are running the latest version of this add-on.
 System: HassOS 3.11  (amd64 / qemux86-64)
 Home Assistant version: 0.105.5
 Supervisor version: 201

## Proposed changes
Unknown

**Comment by nhorvath** [comment]
![image](https://user-images.githubusercontent.com/165084/75154208-3da0db00-56db-11ea-80fd-e23693dd13b6.png)

**Comment by nhorvath** [comment]
So i tried another hard refresh with the console open to make sure I didn't miss anything and it loaded. I don't know what it could have been. I waited literally overnight before refreshing before reporting this and then refreshing a few times this morning after the addon restart.

**Comment by zigt1301** [comment]
I'm having a similar issue where the web page constantly refreshes. I did not have this problem before but it was not working well either, just the constantly spinning home page.

 Add-on version: 1.2.0
 You are running the latest version of this add-on.
 System: HassOS 3.11  (amd64 / qemux86-64)
 Home Assistant Core: 0.106.5
 Home Assistant Supervisor: 208
