### ISSUE TITLE
WARNING: $.fn.slider namespace is already bound. Use the $.fn.bootstrapSlider namespace instead.

### ISSUE THREAD

**Issue by 0evmc** [hassio-addons/addon-phlex#7]
**Phlex UI no longer loads**. 
Originally this component worked exactly as expected and described.
Now, the web page loads and the Plex login prompt appears. After the Plex login, one of the background images appears as always, but no part of the actual UI appears, and the API URL no longer functions or returns any results.
The Browser console shows:

> WARNING: $.fn.slider namespace is already bound. Use the $.fn.bootstrapSlider namespace instead.

> Uncaught SyntaxError: Unexpected token u in JSON at position 0
>     at JSON.parse (<anonymous>)
>     at buildUiDeferred (main.js:147)
>     at parseServerData (main.js:342)
>     at updateStatus (main.js:318)

## Expected behavior
I expect the UI to appear as in the screenshot / as it did when first installed, which can be used to send commands and cause a Plex Movie to play on the destination device.

## Actual behavior
Initial web page appears, Plex login appears, but Phlex user interface no longer appears and Browser shows console errors listed above.

## Steps to reproduce
1. navigate to https://{ip or hostname}:1778
2. Receive results described above
or
1. enter https://{ip or hostname}:1778//api.php?say&apiToken={token}&command=Words+to+Send
2. receive blank page

No update was done before it stopped working. A reboot has occurred recently, but it is not confirmed whether the component began having issues immediately after that. 
- Home Assistant 0.88.1
- No Phlex updates detected.

## Proposed changes
I do not understand the true nature of this issue or how to fix or work around it.
- Tried uninstalling Phlex and reinstalling via the Home Assistant GUI. Don't know how to manually ensure all traces are removed. The issue remains. Unsure what to try since uninstall/re-install didn't work.
______________________
If I have left something out of the info above or you have suggestions, I'm very interested in getting this resolved.

**Comment by frenck** [comment]
This issue is fixed in the current release `v1.1.0`.
